name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11.0"
          
      
      # For more info: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install pipenv
        run: |
          pip install pipenv

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv requirements > requirements.txt
          mkdir -p python
          pipenv run pip install -r requirements.txt -t python/lib/python3.9/site-packages

      - name: Zip it all up and upload to S3
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        env:
          release_bucket: python-lambda-pkg-install
          release_bucket_uri: s3://python-lambda-pkg-install
          release_id: ${{ format('blood-bank-svc-lambda-layer-{0}-dev.zip', github.head_ref )}}
          release_layer: ${{ format('blood-bank-svc-lambda-layer-{0}-dev', github.head_ref )}}
        run: |
          # zip it up
          zip --quiet -r $release_id python
          
          # copy the file to S3 and install it in lambda layers
          aws s3 cp $release_id $release_bucket_uri
          aws lambda publish-layer-version --layer-name $release_layer  --content S3Bucket=$release_bucket,S3Key=$release_id --compatible-runtimes python3.9

      - name: cleaning
        run: rm -rf build layer.zip python
        
      - name: zip lambda
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: blood-bank-svc
          zip_file: bundle.zip
